{% set version = "2.3.0" %}

package:
  name: udkm1dsim
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/udkm1Dsim/udkm1dsim-{{ version }}.tar.gz
  sha256: 6f4766fd2ab2691d0f5e8df1b81c19ae36c5a03df13c1783e05bcb18a8ea86d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - tqdm >=4.43.0
    - numpy
    - pint >=0.23
    - scipy >=1.4.1
    - sympy >=1.5.1
    - tabulate
    - matplotlib-base >=2.0.0

test:
  imports:
    - udkm1Dsim
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dschick/udkm1Dsim
  summary: A Python Simulation Toolkit for 1D Ultrafast Dynamics in Condensed Matter
  license: MIT
  license_file: LICENSE
  doc_url: https://udkm1dsim.readthedocs.io
  dev_url: https://github.com/dschick/udkm1Dsim

extra:
  recipe-maintainers:
    - dschick
